version: '3' 
services: 

  tool-node:
    build: ./tool-node/
    image: localhost.localdomain:5000/immabe/tool_node
    container_name: tool-node
    volumes: 
        - tool-data:/app/data/
    ports: 
        - 5001:5000
    environment: 
        PORT: 5000
        FLASK_DEBUG: 1
    networks:
      dev_net:
        ipv4_address: 172.27.1.5

  registration-node:
    build: ./reg-node/
    image: localhost.localdomain:5000/immabe/registration_node
    container_name: reg-node
    volumes: 
        - reg-data:/app/data/
    ports: 
        - 5002:5000
    environment: 
        PORT: 5000
        FLASK_DEBUG: 1
    networks:
      dev_net:
        ipv4_address: 172.27.1.6

  mysql_dbcontainer:
    image: mysql:latest
    container_name: mysql_db_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    networks:
      dev_net:
        ipv4_address: 172.27.1.7
 
  adminer_container:
     image: adminer:latest
     environment:
       ADMINER_DEFAULT_SERVER: mysql_db_container
     ports:
      - 8080:8080
     networks:
       dev_net:
         ipv4_address: 172.27.1.8

#mounted filesystems on the node to preserve data generated by the running containers
volumes:
  tool-data:
  reg-data:
  mysql_db_data_container:

networks:
  dev_net:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
